micronaut:
  application:
    name: testApi
  server:
    port : 5000
    cors:
      enabled: true

datasources:
  default:
    driver-class-name: ${DATASOURCE_DEFAULT_DRIVER:org.mariadb.jdbc.Driver}
    db-type: mariadb
    dialect: MYSQL
    jdbc-url: ${DATASOURCE_DEFAULT_URL:`jdbc:mariadb://localhost:3306/Pokemon`}
    username: ${DATASOURCE_DEFAULT_USER:example-user}
    password: ${DATASOURCE_DEFAULT_PASSWORD:my_cool_secret}

liquibase:
  datasources:
    default:
      change-log: classpath:db/liquibase-changelog.yml
netty:
  default:
    allocator:
      max-order: 3
